# Generated by Django 4.2.6 on 2023-10-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_friends_delete_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
        migrations.AddField(
            model_name='user',
            name='board',
            field=models.ForeignKey(default=616161, on_delete=django.db.models.deletion.CASCADE, to='main.board'),
            preserve_default=False,
        ),
    ]
