# Generated by Django 4.2.6 on 2023-10-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_board_owner_user_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardColor',
            field=models.ForeignKey(default='616161', on_delete=django.db.models.deletion.CASCADE, to='main.colors'),
        ),
    ]
