# Generated by Django 4.2.6 on 2023-10-13 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_board_boardcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='board',
        ),
        migrations.RemoveField(
            model_name='user',
            name='board',
        ),
        migrations.AddField(
            model_name='user',
            name='askBeforeStick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='boardColor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.colors'),
        ),
        migrations.AddField(
            model_name='user',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stickersOnBoard',
            field=models.ManyToManyField(to='main.sticker'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
