# Generated by Django 4.2.6 on 2023-10-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_sticker_board_remove_user_board_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
    ]
