# Generated by Django 4.2.6 on 2023-10-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_colors_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boardColor',
            field=models.ForeignKey(default='616161', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.color'),
        ),
    ]
