# Generated by Django 4.2.6 on 2023-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_boardcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stickersOnBoard',
            field=models.ManyToManyField(default=0, to='main.sticker'),
        ),
    ]
