# Generated by Django 4.2.6 on 2023-10-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_stickersonboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boardColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.color'),
        ),
    ]
