# Generated by Django 4.2.6 on 2023-10-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boardColor',
            field=models.ForeignKey(blank=True, default='616161', on_delete=django.db.models.deletion.CASCADE, to='main.color'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stickersOnBoard',
            field=models.ManyToManyField(blank=True, to='main.sticker'),
        ),
    ]
