# Generated by Django 4.2.6 on 2023-10-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_boardcolor_alter_user_stickersonboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='boardColor',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
