# Generated by Django 4.2.6 on 2023-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending',
            field=models.ManyToManyField(blank=True, related_name='pending_stickers', to='main.sticker'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stickersOnBoard',
            field=models.ManyToManyField(blank=True, related_name='stickers_on_board', to='main.sticker'),
        ),
    ]
