# Generated by Django 4.2.6 on 2023-12-08 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_user_pending_alter_user_stickersonboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_requests',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
